---
- name: apt-unattended-upgrades role
  tags: [role-apt-unattended-upgrades]
  block:

  # debug
  - when: false
    ansible.builtin.debug:
      msg: "{{ unattended_upgrades }}"
  
  # check
  - name: Check vars for unattended-upgrades role
    ansible.builtin.assert:
      that:
      - unattended_upgrades_config_template != None
      - unattended_upgrades_config_vars['mail'] != None

  # install
  - ansible.builtin.import_tasks: apt-unattended-upgrades-install.yml

  # systemd
  - ansible.builtin.import_tasks: apt-unattended-upgrades-systemd.yml

  # config
  - ansible.builtin.import_tasks: apt-unattended-upgrades-config.yml

  # listchanges
  - ansible.builtin.import_tasks: apt-unattended-upgrades-listchanges.yml